### ISSUE TITLE
handbrake watcher closes if handbrake conversion fails

### ISSUE THREAD

**Issue by cyturralde** [shannah/handbrake-watcher#1]
If a file does not convert for any reason, handbrake watcher closes. Not sure if there is a way to make it restart automatically.

**Comment by shannah** [comment]
It shouldn't close.  Can you post the a snippet of the console readout when this happens?

**Comment by cyturralde** [comment]
Ive manually restarted it the last time it happened, but the next time it happens I will post a screen shot of the command console if that works.

**Comment by cyturralde** [comment]
It seems it is also closing on completion of an encode somtimes. Here is a screenshot: 
![capture](https://user-images.githubusercontent.com/5245370/33900754-991f6d88-df3d-11e7-8e6c-6598d6ae2e85.PNG)

**Comment by shannah** [comment]
Are you sure that it has exited.  THe "HandBrake has exited" message comes from the handbrake sub-process.  The watcher should still be scanning after that is done.

**Comment by cyturralde** [comment]
I am not sure how I would verify that. When the program first starts it says watching ..
I guess I just assumed it would go back to that at the end. I'll let a couple files download over the next few days and see if it keeps going regardless of the Handbrake has exited, and report back. Thanks again for all the help.
