### ISSUE TITLE
Should pass option without "=" sign

### ISSUE THREAD

**Issue by christian-0s** [shannah/handbrake-watcher#10]
I tried to use a preset file, but specifing in file handbrake.properties:
`handbrake.options.preset-import-file presets.json`
I get the error message:
`unknown option (--preset-import-file=presets.json)`
The option should be passed as --preset-import-file presets.json without "="

**Comment by pkoerner81929** [comment]
Same here. Did you find a solution?

**Comment by christian-0s** [comment]
Unfortunately no, I gave up on this

**Comment by pkoerner81929** [comment]
Ok, thanks. Any alternative you found? I need to select a specific preset using NVenc settings but could no find a way to select. The HandBrakeCLI presets are not matching the GUI presets, so I had to pass the options somehow. Actually, a way around handbrake-watcher would also be fine...

**Comment by christian-0s** [comment]
Sorry I cannot help, as I changed approach completely

**Comment by shannah** [comment]
Just fixed this and pushed a new version to npm 1.1.15

**Comment by pkoerner81929** [comment]
Hey, that's good news, will try asap.

**Comment by pkoerner81929** [comment]
Works. Thanks again.
