### ISSUE TITLE
Can't set the optimizeMp4 option

### ISSUE THREAD

**Issue by bzh4bzh** [shannah/handbrake-watcher#11]
Not sure how to set it, I tried flags and options. Prefer to set up config files.

**Comment by shannah** [comment]
Isn't that just the `--optimize` flag (https://handbrake.fr/docs/en/latest/cli/command-line-reference.html)

In this case you would use the `handbrake.flags` property.   I.e. `handbrake.flags=--optimize`  You can set this on the command-line using `-Dhandbrake.flags=--optimize`, or in your `handbrake.properties` file with `handbake.flags=--optimize`
