### ISSUE TITLE
Add support for Handbrake 1.2.0

### ISSUE THREAD

**Issue by shannah** [shannah/handbrake-watcher#13]
The default preset of "High Profile" is no longer available in Handbrake 1.2.0.
We need to detect Handbrake version and set the preset to "HQ 1080p30 Surround" if the version is 1.2.0 or higher.

**Comment by shannah** [comment]
New presets are listed at https://handbrake.fr/docs/en/1.2.0/technical/official-presets.html

**Comment by hg1233** [comment]
A way of potentially doing this is to run the HandbrakeCLI with the --version flag, obtain the output and check if it is a certain version, if so then change the default preset to Fast 1080p30 for example.

**Comment by shannah** [comment]
Yes.  That is what I was thinking too.  Just haven't had a chance to get around to it.

**Comment by shannah** [comment]
Changed default preset to one that is in the latest handbrake cli.
