### ISSUE TITLE
Inflexible destination directory.

### ISSUE THREAD

**Issue by Paddywaan-zz** [shannah/handbrake-watcher#18]
If ones purpose is to re-encode the the source using a different codec while retaining the same filename and ext, the watcher refuses to convert. After taking a quick look through the helptext and code base i was unable to find any option to specify a destination directory. Having the flexibility to specify a directory for completed encodes would be a useful addition which would also resolve this particular issue I face.

**Comment by OlaDates** [comment]
I'm also having this issue of not being able to set a destination folder for encodes

**Comment by Rings4** [comment]
I would like this as well. I cannot use this as it is because I need the output to go to a completely different folder.

**Comment by shannahcloudbeds** [comment]
I have just published version 1.0.18 which adds support for a `destination.dir` config option in the handbrake.properties file.

E.g.

```
destination.dir=${src.dir}/handbrake-converted
```

This version also adds support for ignoring directories by adding a .handbrake-ignore file to the directory you want to ignore.

**Comment by shannah** [comment]
I have just published version 1.0.18 which adds support for a destination.dir config option in the handbrake.properties file.

E.g.

```
destination.dir=${src.dir}/handbrake-converted
```

This version also adds support for ignoring directories by adding a .handbrake-ignore file to the directory you want to ignore.

**Comment by Rings4** [comment]
Great, how do you update? I can't seem to figure that out. I still have 1.0.14.

**Comment by shannah** [comment]
`sudo npm install -g handbrake-watcher`

**Comment by Rings4** [comment]
> `sudo npm install -g handbrake-watcher`

I'm on windows. I did npm install -g handbrake-watcher. Still 1.0.14.

**Comment by shannah** [comment]
If you run `npm list -g`, what does it say for handbrake-watcher.

For me, it shows `├── handbrake-watcher@1.0.18`

**Comment by Rings4** [comment]
Strange, it shows the same for me, but not when I actually run handbrake-watcher.

![image](https://github.com/shannah/handbrake-watcher/assets/32050292/1746b7eb-3095-4ec1-a315-8fa101226f8a)

**Comment by shannah** [comment]
Oops.  Looks like that "v1.0.14" comes from a hard-coded constant that I forgot to update. 
https://github.com/shannah/handbrake-watcher/blob/36cef5696378d4c83ec9937f18f432df046b51dc/src/ca/weblite/handbrake/HandbrakeWatcher.java#L26

So you're on version 1.0.18, despite what handbrake watcher is telling you.

I'm guessing that NullPointerException is a manifestation of a permission error because you're running it in the system32 directory.  I'll look into dealing with that situation more gracefully.

**Comment by Rings4** [comment]
Ah you're right, it's working. I had to run hadnbrake-watcher from within the correct folder. Thanks!

> I have just published version 1.0.18 which adds support for a destination.dir config option in the handbrake.properties file.
> 
> E.g.
> 
> ```
> destination.dir=${src.dir}/handbrake-converted
> ```
> 
> This version also adds support for ignoring directories by adding a .handbrake-ignore file to the directory you want to ignore.

Just one question on this: if I want my output to be in 

C:\\Users\\myusername\\Documents\\S\\Handbrake Watcher Output

how would I format it? I tried the following but no luck:

destination.dir=$C:\\Users\\myusername\\Documents\\S\\Handbrake Watcher Output

**Comment by shannah** [comment]
That's a kind of annoyance of the .properties file format.
You need to escape the backslashes:

E.g.

```
destination.dir=C:\\Users\\myusername\\Documents\\S\\Handbrake Watcher Output
```

https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html

**Comment by Rings4** [comment]
> That's a kind of annoyance of the .properties file format. You need to escape the backslashes:
> 
> E.g.
> 
> ```
> destination.dir=C:\\Users\\myusername\\Documents\\S\\Handbrake Watcher Output
> ```
> 
> https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html

Ah thank you, I figured that was the case shortly after commenting. I do have one last question:

If I want my output to be in a subfolder that's named the same as the source subfolder the file is in, how do I do that? For example:

C:\\Input\\Recording 1\\game.mp4

should go to

C:\\Output\\Recording 1\\game.m4v

In Handbrake's GUI, it has {source_folder_name} that accomplishes this. Does your tool or HandbrakeCLI have the same functionality?
