### ISSUE TITLE
shelljs is no longer valid

### ISSUE THREAD

**Issue by heldmar** [shannah/handbrake-watcher#19]
This excellent, simple and optimal watcher no longer works. I have been using it for years, and recently my server suffered a hard disk failure and I lost a lot of things, including this script! I tried downloading it again, but when trying to install it I receive a message saying shelljs is no longer valid.

I am no developer, although I understand most of the code, however, I couldn't make this work, even by redownloading shelljs in its 0.8.5 version, which is the latest.

@shannah can you update this script for once please? It is so useful and it would be great to be able to use it again.

Thank you in advance, I hope you are in good spirits.

**Comment by shannah** [comment]
Thanks.  Will publish a new version on Saturday

**Comment by heldmar** [comment]
Thanks so much! I was able to install this (it seems I was not understanding the npm installation process and npm different set of options when installing, like ignoring the auditing, etc). Still, I really appreciate your work, and honestly, I couldn't find any other handbrake handler or watcher like this one. This is the best!

**Comment by shannah** [comment]
Fixed in version 1.0.18
