### ISSUE TITLE
Is there anyway to make it also convert .ts files?

### ISSUE THREAD

**Issue by cyturralde** [shannah/handbrake-watcher#2]

**Comment by shannah** [comment]
Yes.  Create a file named "handbrake.properties" in the same directory that you run handbrake-watcher from.  The contents should be

~~~~
source.extension=ts
~~~~

**Comment by cyturralde** [comment]
Wow thanks for the quick response. If I put source.extension=ts, mkv will it do both?

**Comment by shannah** [comment]
I just published a new version (1.0.13) that will allow you to set properties on the command line.  So you can do

~~~~
handbrake-watcher -Dsource.extension=ts
~~~~

You can't do "ts,mkv", but you can run two instances of handbrake-watcher on the same directory at simultaneously.  E.g.

~~~~
handbrake-watcher -Dsource.extension=ts &
handbrake-watcher -Dsource.extension=mkv &
~~~~

**Comment by cyturralde** [comment]
first let me say, you are probably the quickest responding developer I have met. Thank you for the great program. As a final question can I road that in one command line or do I need two seperate command windows open

**Comment by shannah** [comment]
On linux/BSD/OSX the "&" at the end of each line tells it to run as a daemon - so you can run them in the same window.  If you leave out the "&" you'd need two windows.   Two windows might be easier to manage anyways as in daemon mode it may be harder to identify when the script crashes or stalls.

I'm not sure how to do the same in Windows as I don't use windows much.
