### ISSUE TITLE
Cannot import preset file

### ISSUE THREAD

**Issue by Rings4** [shannah/handbrake-watcher#20]
How do you import a preset file?

My .properties file includes the following:

`handbrake.options.preset-import-file="C:\Users\myusername\Documents\S\Handbrake Watcher\Handbrake Preset - Game Recordings New H265 2023-03-26.json"
handbrake.options.preset="Game Recordings New H265"`

but it doesn't accept it.

**Comment by shannah** [comment]
.properties files should have one key=value per line, and don't use quotes around values.  You'll need to escape the back-slashes also.  E.g.

```
handbrake.options.preset-import-file=C:\\Users\\myusername\\Documents\\S\\Handbrake Watcher\\Handbrake Preset - Game Recordings New H265 2023-03-26.json
handbrake.options.preset=Game Recordings New H265
```

See https://en.wikipedia.org/wiki/.properties for details about the syntax.
