### ISSUE TITLE
Multiple Source Extensions

### ISSUE THREAD

**Issue by jlhunter2008** [shannah/handbrake-watcher#7]
Is there a way to have multiple source extensions for handbrake-watcher to look for? If so, how should they be added to the .properties file.

**Comment by shannah** [comment]
Just added support for this https://github.com/shannah/handbrake-watcher/commit/92452c6a19a6184c896171aa50465b63a29258f5

Will be updating on NPM shortly.

**Comment by shannah** [comment]
Example:

~~~~
source.extension=mkv MKV avi
~~~~

I.e. just add multiple in the source.extension property, separated by spaces.
